language: python
python:
  - "2.7_with_system_site_packages"
  - 3.3

# workaround for scipy..
# install scipy with the default package manager, pip does not install the necessities
before_install:
  - sudo apt-get install -qq python-numpy python-scipy

# for most pip-packages, the following approach should work:
#install: pip install numpy --use-mirrors

# command to run tests, e.g. python setup.py test
script: python setup.py test
