language: python

python:
  - 2.7
  - 3.3

notifications:
  email: true

# Setup anaconda - adapted from https://gist.github.com/dan-blanchard/7045057
# This is mainly to work around an issue when installing scipy via pip
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - sudo apt-get -qq install graphviz > /dev/null
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose pygraphviz pillow
  - python setup.py install
  - pip install coveralls

# run tests and collect coverage data
script: 
    coverage run --source=drunkenmarkov setup.py test

# submit coverage data to coveralls
after_success:
    coveralls
